### ISSUE TITLE
Seg fault after set_mapsize failure

### ISSUE THREAD

**Issue by jnwatson** [jnwatson/py-lmdb#164]
### Affected Operating Systems

* Windows
* MacOS
32-bit cpython interpreter only.

### Affected py-lmdb Version

0.92

### py-lmdb Installation Method

pip

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

Use "print lmdb.version()" from a Python prompt.
`(0, 9, 18)`
### Machine "free -m" output
N/A (not on Linux)

### Other important machine info

Seen on Windows 7, Windows 10, Mac OS 10.12.5, 32-bit interpreter

### Describe Your Problem

XXXXX

### Errors/exceptions Encountered

e.g.

```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmdb
>>> dbenv = lmdb.Environment('foo.lmdb')
>>> dbenv.set_mapsize(2**31-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lmdb.Error: mdb_env_set_mapsize: Not enough storage is available to process this command.

>>> dbenv.info()
(interpreter crash)
```
Note that, in this case, there is ample free storage and RAM.

### Describe What You Expected To Happen
Not crash

### Describe What Happened Instead
The Python process crashed.

**Comment by jnwatson** [comment]
Can duplicate on 64-bit interpreter on MacOS as well.
```
>>> dbenv.set_mapsize(2**47)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lmdb.MemoryError: mdb_env_set_mapsize: Cannot allocate memory
>>> dbenv.info()
Segmentation fault: 11
```

Sounds like the error path code could use some love.

**Comment by dw** [comment]
Related: #96 

I think I've come across this one before but never got around to fixing it, it looks like a bug in the engine not the binding

**Comment by dw** [comment]
````
gdb --args /usr/bin/python2.7
Reading symbols from /usr/bin/python2.7...Reading symbols from /usr/lib/debug//usr/bin/python2.7...done.
done.
(gdb)
(gdb)
(gdb) run
Starting program: /usr/bin/python2.7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lmdb
>>> env = lmdb.open('derp')
>>> env.set_mapsize(2**50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
lmdb.MemoryError: mdb_env_set_mapsize: Cannot allocate memory
>>> env.set_mapsize(2**40)
>>>
>>>
>>> env.info()

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6335064 in mdb_env_pick_meta (env=0xa6fff0) at lib/mdb.c:3904
3904            return metas[ metas[0]->mm_txnid < metas[1]->mm_txnid ];
(gdb) bt
#0  0x00007ffff6335064 in mdb_env_pick_meta (env=0xa6fff0) at lib/mdb.c:3904
#1  mdb_env_info (env=0xa6fff0, arg=arg@entry=0x7fffffffe100) at lib/mdb.c:9632
#2  0x00007ffff63257a6 in env_info (self=0x7ffff6eca750) at lmdb/cpython.c:1485
#3  0x00000000004c9d4a in call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4017
#4  PyEval_EvalFrameEx () at ../Python/ceval.c:2679
#5  0x00000000004c7a59 in PyEval_EvalCodeEx () at ../Python/ceval.c:3265
#6  0x000000000050160f in PyEval_EvalCode (
    locals={'__builtins__': <module at remote 0x7ffff7f98b08>, '__package__': None, 'env': <Environment at remote 0x7ffff6eca750>, '__name__': '__main__', 'lmdb': <module at remote 0x7ffff6ec4328>, '__doc__': None},
    globals={'__builtins__': <module at remote 0x7ffff7f98b08>, '__package__': None, 'env': <Environment at remote 0x7ffff6eca750>, '__name__': '__main__', 'lmdb': <module at remote 0x7ffff6ec4328>, '__doc__': None}, co=0x7ffff7e57f30) at ../Python/ceval.c:667
#7  run_mod.lto_priv () at ../Python/pythonrun.c:1371
#8  0x00000000004495f2 in PyRun_InteractiveOneFlags (fp=0xa6fff0, fp@entry=0x7ffff72974e0 <_IO_2_1_stdin_>, filename=0x7fffffffe100 "`\001\247",
    filename@entry=0x603d84 "<stdin>", flags=0x7fffffffe470) at ../Python/pythonrun.c:858
#9  0x000000000044941e in PyRun_InteractiveLoopFlags (fp=fp@entry=0x7ffff72974e0 <_IO_2_1_stdin_>, filename=filename@entry=0x603d84 "<stdin>", flags=flags@entry=0x7fffffffe470)
    at ../Python/pythonrun.c:778
#10 0x000000000042d405 in PyRun_AnyFileExFlags (fp=0x7ffff72974e0 <_IO_2_1_stdin_>, filename=<optimized out>, closeit=0, flags=0x7fffffffe470) at ../Python/pythonrun.c:747
#11 0x00000000004981cd in Py_Main () at ../Modules/main.c:640
#12 0x00007ffff6f12b45 in __libc_start_main (main=0x497c60 <main>, argc=1, argv=0x7fffffffe638, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe628) at libc-start.c:287
#13 0x0000000000497b8b in _start ()
(gdb)
(gdb) info reg
rax            0x7ffff561b010   140737310208016
rbx            0x7ffff6eca750   140737336092496
rcx            0x93c280 9683584
rdx            0x6      6
rsi            0x7fffffffe100   140737488347392
rdi            0xa6fff0 10944496
rbp            0x7ffff7ebe518   0x7ffff7ebe518
rsp            0x7fffffffe0f8   0x7fffffffe0f8
r8             0x1      1
r9             0x7ffff6eca750   140737336092496
r10            0x7ffff7ebe520   140737352820000
r11            0x938480 9667712
r12            0x9ad0a0 10145952
r13            0x0      0
r14            0x7ffff6325770   140737323882352
r15            0x7ffff6ec4485   140737336067205
rip            0x7ffff6335064   0x7ffff6335064 <mdb_env_info+20>
eflags         0x10206  [ PF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb) p/i $pc
Format letter "i" is meaningless in "print" command.
(gdb) l
3899     */
3900    static MDB_meta *
3901    mdb_env_pick_meta(const MDB_env *env)
3902    {
3903            MDB_meta *const *metas = env->me_metas;
3904            return metas[ metas[0]->mm_txnid < metas[1]->mm_txnid ];
3905    }
3906
3907    int ESECT
3908    mdb_env_create(MDB_env **env)
```

**Comment by jnwatson** [comment]
I've run into this problem on Windows 32-bit. Fragmentation of the limited 4-GiB virtual address space is the culprit.
