### ISSUE TITLE
Failed tests/crash_test.py: ReadonlyError on ppc64le

### ISSUE THREAD

**Issue by skupr-anaconda** [jnwatson/py-lmdb#295]
### Affected Operating Systems

* ppc64le

### Affected py-lmdb Version

python-lmdb-1.2.1

### py-lmdb Installation Method

  conda build

### Describe Your Problem

Tests fail on linux ppc64le with py36-py39

### Errors/exceptions Encountered

```
Packaging python-lmdb
INFO:conda_build.build:Packaging python-lmdb
INFO conda_build.build:build(2274): Packaging python-lmdb
Packaging python-lmdb-1.2.1-py38h29c3540_1
INFO:conda_build.build:Packaging python-lmdb-1.2.1-py38h29c3540_1
INFO conda_build.build:bundle_conda(1514): Packaging python-lmdb-1.2.1-py38h29c3540_1
compiling .pyc files...
number of files: 19
Warning: rpath /root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/lib is outside prefix /root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho (removing it)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libtinfo.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libhistory.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libmenu.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libreadline.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libncurses++w.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libformw.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libpython3.8.nolto.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libtkstub8.6.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/liblzma.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libz.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libtclstub8.6.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libncursesw.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libcrypto.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libpanelw.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libffi.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libpython3.8.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libssl.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/itcl4.2.0/libitclstub4.2.0.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/tdbc1.1.1/libtdbcstub1.1.1.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/lib/libiberty.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/libgcc.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/libgcov.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/libgcc_eh.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/lib/libsupc++.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/lib/libstdc++.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/lib/libstdc++fs.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libdl.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libnsl.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libbsd-compat.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libc.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libutil.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/librt.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libnldbl_nonshared.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libBrokenLocale.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libcrypt.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libc_nonshared.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libresolv.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libpthread_nonshared.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libanl.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libm.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/libpthread.a)
WARNING :: Failed to get_static_lib_exports(/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/lib/librpcsvc.a)
   INFO: sysroot: '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/' files: '['/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/share/locale/zh_TW/LC_MESSAGES/libc.mo', '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/share/locale/zh_CN/LC_MESSAGES/libc.mo', '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/share/locale/vi/LC_MESSAGES/libc.mo', '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_build_env/powerpc64le-conda_cos7-linux-gnu/sysroot/usr/share/locale/tr/LC_MESSAGES/libc.mo']'
   INFO (python-lmdb,lib/python3.8/site-packages/lmdb/cpython.cpython-38-powerpc64le-linux-gnu.so): Needed DSO powerpc64le-conda_cos7-linux-gnu/sysroot/lib/libpthread.so.0 found in CDT/compiler package defaults::gcc_impl_linux-ppc64le-7.3.0-he01c8ba_1
   INFO (python-lmdb,lib/python3.8/site-packages/lmdb/cpython.cpython-38-powerpc64le-linux-gnu.so): Needed DSO powerpc64le-conda_cos7-linux-gnu/sysroot/lib/libc.so.6 found in CDT/compiler package defaults::gcc_impl_linux-ppc64le-7.3.0-he01c8ba_1
WARNING (python-lmdb): interpreter (Python) package pkgs/main::python-3.8.8-h836d2c2_5 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
Fixing permissions
Packaged license file/s.
INFO :: Time taken to mark (prefix)
        0 replacements in 0 files was 0.00 seconds
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING conda_build.build:bundle_conda(1687): Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
TEST START: output-artifacts/linux-ppc64le/python-lmdb-1.2.1-py38h29c3540_1.tar.bz2
Renaming work directory '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work' to '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le'
INFO:conda_build.utils:Renaming work directory '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work' to '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le'
INFO conda_build.utils:shutil_move_more_retrying(2077): Renaming work directory '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work' to '/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le'
shutil.move(work)=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work, dest=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le)
INFO:conda_build.utils:shutil.move(work)=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work, dest=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le)
INFO conda_build.utils:shutil_move_more_retrying(2084): shutil.move(work)=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work, dest=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/work_moved_python-lmdb-1.2.1-py38h29c3540_1_linux-ppc64le)
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    _libgcc_mutex:         0.1-main                                                                                            
    attrs:                 20.3.0-pyhd3eb1b0_0                                                                                 
    ca-certificates:       2021.4.13-h6ffa863_1                                                                                
    iniconfig:             1.1.1-pyhd3eb1b0_0                                                                                  
    ld_impl_linux-ppc64le: 2.33.1-h0f24833_7                                                                                   
    libffi:                3.3-he6710b0_2                                                                                      
    libgcc-ng:             8.2.0-h822a55f_1                                                                                    
    libstdcxx-ng:          8.2.0-h822a55f_1                                                                                    
    more-itertools:        8.7.0-pyhd3eb1b0_0                                                                                  
    ncurses:               6.2-he6710b0_1                                                                                      
    openssl:               1.1.1k-h140841e_0                                                                                   
    packaging:             20.9-pyhd3eb1b0_0                                                                                   
    pluggy:                0.13.1-py38h6ffa863_0                                                                               
    py:                    1.10.0-pyhd3eb1b0_0                                                                                 
    pyparsing:             2.4.7-pyhd3eb1b0_0                                                                                  
    pytest:                6.2.3-py38h6ffa863_2                                                                                
    python:                3.8.8-h836d2c2_5                                                                                    
    python-lmdb:           1.2.1-py38h29c3540_1  file:///root/worker/containers/00000a7rlau/tmp/build/80754af9/output-artifacts
    readline:              8.1-h140841e_0                                                                                      
    six:                   1.15.0-py38h6ffa863_0                                                                               
    sqlite:                3.35.4-hd7247d8_0                                                                                   
    tk:                    8.6.10-hbc83047_0                                                                                   
    toml:                  0.10.2-pyhd3eb1b0_0                                                                                 
    xz:                    5.2.5-h7b6447c_0                                                                                    
    zlib:                  1.2.11-h7b6447c_3                                                                                   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/root/worker/containers/00000a7rlau/tmp/build/80754af9/python-lmdb_1619391259780/test_tmp
import: 'lmdb'
import: 'lmdb'
+ py.test tests
============================= test session starts ==============================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: $SRC_DIR
collected 190 items

tests/crash_test.py ..................F                                  [ 10%]
tests/cursor_test.py .............................                       [ 25%]
tests/env_test.py ...................................................... [ 53%]
..............                                                           [ 61%]
tests/getmulti_test.py ....                                              [ 63%]
tests/iteration_test.py ..................                               [ 72%]
tests/package_test.py .                                                  [ 73%]
tests/tool_test.py ..                                                    [ 74%]
tests/txn_test.py .................................................      [100%]

=================================== FAILURES ===================================
_______________________ MapResizeTest.test_opendb_resize _______________________

self = <crash_test.MapResizeTest testMethod=test_opendb_resize>

    def test_opendb_resize(self):
        '''
        Test that we correctly handle a MDB_MAP_RESIZED in env.open_db.
    
        Would seg fault in cffi implementation
        '''
        mpctx = multiprocessing.get_context('spawn')
        path, env = testlib.temp_env(max_dbs=10, map_size=32000)
        env.close()
        env = lmdb.open(path, max_dbs=10, map_size=32000, readonly=True)
        proc = mpctx.Process(target=self.do_resize, args=(path,))
        proc.start()
        proc.join(5)
        assert proc.exitcode is not None
>       self.assertRaises(lmdb.MapResizedError, env.open_db, b'foo')
E       lmdb.ReadonlyError: mdb_dbi_open: Permission denied

tests/crash_test.py:316: ReadonlyError
----------------------------- Captured stderr call -----------------------------
Process SpawnProcess-1:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$PREFIX/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "$SRC_DIR/tests/crash_test.py", line 296, in do_resize
    env.open_db(b'foo')
lmdb.MapFullError: mdb_dbi_open: MDB_MAP_FULL: Environment mapsize limit reached
=========================== short test summary info ============================
FAILED tests/crash_test.py::MapResizeTest::test_opendb_resize - lmdb.Readonly...
======================== 1 failed, 189 passed in 9.78s =========================
Tests failed for python-lmdb-1.2.1-py38h29c3540_1.tar.bz2 - moving package to /root/worker/containers/00000a7rlau/tmp/build/80754af9/broken
WARNING:conda_build.build:Tests failed for python-lmdb-1.2.1-py38h29c3540_1.tar.bz2 - moving package to /root/worker/containers/00000a7rlau/tmp/build/80754af9/broken
WARNING conda_build.build:tests_failed(2955): Tests failed for python-lmdb-1.2.1-py38h29c3540_1.tar.bz2 - moving package to /root/worker/containers/00000a7rlau/tmp/build/80754af9/broken
TESTS FAILED: python-lmdb-1.2.1-py38h29c3540_1.tar.bz2

```

### Describe What You Expected To Happen

I expected the tests pass successfully.

### Describe What Happened Instead

Tests failed.

**Comment by jnwatson** [comment]
Do you have any ideas as to how I can interact with a ppc64le platform? Is there a virtualization system that works well?

**Comment by jnwatson** [comment]
With some effort, I am able to duplicate your problem. Some initial investigation reveals the core problem is the page size. The page size of ppc64le on Debian and others is 64K, which is quite unusual. Regardless, this is a test-only problem. I'll have the test fixed up soon.

**Comment by jnwatson** [comment]
This is resolved in master.
