### ISSUE TITLE
py-lmdb: Using system version of liblmdb. Using cffi extension. /usr/bin/ld: cannot open linker script file python.map: No such file or directory

### ISSUE THREAD

**Issue by monajalal** [jnwatson/py-lmdb#348]
```
 1446  export CFLAGS="-I/home/mona/Python-3.5.3/Include"
 1447  cd ../py-lmdb/
 1448  python setup.py install
 1449  cd ../Python-3.5.3/
 1450  find . -name python.map --> find none
 1454  cd py-lmdb/
 1455  python setup.py install
 1456  LMDB_FORCE_SYSTEM=1 python setup.py install
 1459  sudo apt install liblmdb-dev
 1460  export LMDB_FORCE_SYSTEM=1
 1461  python setup.py install
 1464  sudo apt install build-essential
 1465  python setup.py clean
 1466  python setup.py install
 1467  pip install --upgrade setuptools
 1468  python setup.py install
```
and I have:
```
(pvrendering) (base) mona@mona-ThinkStation-P7:~/py-lmdb$ python setup.py install
py-lmdb: Using system version of liblmdb.
Using cffi extension.
/usr/bin/ld: cannot open linker script file python.map: No such file or directory
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/mona/py-lmdb/lmdb/__init__.py", line 41, in <module>
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/unixccompiler.py", line 196, in link
    self.spawn(linker + ld_args)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/mona/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/python/lib/python3.5/distutils/unixccompiler.py", line 198, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 180, in <module>
    import lmdb.cffi
  File "/home/mona/py-lmdb/lmdb/__init__.py", line 48, in <module>
    from lmdb.cffi import *
  File "/home/mona/py-lmdb/lmdb/cffi.py", line 379, in <module>
    library_dirs=_config_vars['extra_library_dirs'])
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/api.py", line 468, in verify
    lib = self.verifier.load_library()
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/verifier.py", line 105, in load_library
    self._compile_module()
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/verifier.py", line 202, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mona/pvnet-rendering/pvrendering/lib/python3.5/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

```

sys info:
```
(pvrendering) (base) mona@mona-ThinkStation-P7:~$ uname -a
Linux mona-ThinkStation-P7 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
(pvrendering) (base) mona@mona-ThinkStation-P7:~$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
(pvrendering) (base) mona@mona-ThinkStation-P7:~$ python --version
Python 3.5.3
(pvrendering) (base) mona@mona-ThinkStation-P7:~$ which python
/home/mona/pvnet-rendering/pvrendering/bin/python

```

**Comment by monajalal** [comment]
```
root@fae597dbdb79:/home/pvnet-rendering# /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/pip3 install lmdb --only-binary=:all:
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting lmdb
  Downloading lmdb-1.2.1-cp35-cp35m-manylinux2010_x86_64.whl (297 kB)
     |################################| 297 kB 7.6 MB/s 
Installing collected packages: lmdb
Successfully installed lmdb-1.2.1

```

https://stackoverflow.com/a/77686148/2414957
